apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitnami-sealed-secrets-app
  namespace: argocd
spec:
  destination:
    namespace: dbc
    server: https://kubernetes.default.svc
  project: default
  source:
    path: examples/bitnami-sealed-secrets/application
    repoURL: https://github.com/gerundium/argocd-tutorial.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true